# Generated by Django 4.2.4 on 2023-11-21 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_co_requisite_alter_course_course_type_and_more'),
        ('accounts', '0003_alter_educationaldeputy_faculty_and_more'),
        ('college', '0002_alter_faculty_name_alter_fieldofstudy_degree_and_more'),
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedrop',
            name='course_drop_status',
            field=models.IntegerField(choices=[('1', 'تایید'), ('2', 'رد درخواست'), ('3', 'در حال بررسی')], default=3, verbose_name='نتیجه ی درخواست'),
        ),
        migrations.AddField(
            model_name='termdrop',
            name='term_drop_status',
            field=models.IntegerField(choices=[('1', 'تایید'), ('2', 'رد درخواست'), ('3', 'در حال بررسی')], default=3, verbose_name='نتیجه درخواست'),
        ),
        migrations.AlterField(
            model_name='coursedrop',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_drop_req_course', to='course.course', verbose_name='درس'),
        ),
        migrations.AlterField(
            model_name='coursedrop',
            name='educational_deputy_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات معاون آموزشی'),
        ),
        migrations.AlterField(
            model_name='coursedrop',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_drop_req_student', to='accounts.student', verbose_name='دانشجو'),
        ),
        migrations.AlterField(
            model_name='coursedrop',
            name='student_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات دانشجو'),
        ),
        migrations.AlterField(
            model_name='enrollmentverification',
            name='enrollment_verification_file',
            field=models.FileField(upload_to='', verbose_name='فایل اشتغال به تحصیل'),
        ),
        migrations.AlterField(
            model_name='enrollmentverification',
            name='issuance_certificate_place',
            field=models.CharField(max_length=200, verbose_name='محل صدور گواهی'),
        ),
        migrations.AlterField(
            model_name='enrollmentverification',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_verification_req_student', to='accounts.student', verbose_name='دانشجو'),
        ),
        migrations.AlterField(
            model_name='enrollmentverification',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_verification_req_term', to='college.term', verbose_name='ترم'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='approval_status',
            field=models.BooleanField(default=False, verbose_name='وضعیت تایید'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='courses',
            field=models.ManyToManyField(to='course.course', verbose_name='دروس درخواستی'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_student', to='accounts.student', verbose_name='دانشجوی درخواست دهنده'),
        ),
        migrations.AlterField(
            model_name='registrationupdate',
            name='add_courses',
            field=models.ManyToManyField(blank=True, related_name='update_taken_course_add', to='course.course', verbose_name='دروس اضافه'),
        ),
        migrations.AlterField(
            model_name='registrationupdate',
            name='approval_status',
            field=models.CharField(choices=[['E', 'درحال انجام توسط دانشجو'], ['P', 'منتظر نظر استاد'], ['A', 'تایید شده'], ['D', 'رد شده']], default='E', max_length=1, verbose_name='وضعیت تایید'),
        ),
        migrations.AlterField(
            model_name='registrationupdate',
            name='del_courses',
            field=models.ManyToManyField(blank=True, related_name='update_taken_course_del', to='course.course', verbose_name='دروس حذف'),
        ),
        migrations.AlterField(
            model_name='registrationupdate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_taken_course_student', to='accounts.student', verbose_name='دانشجو'),
        ),
        migrations.AlterField(
            model_name='reviewgrade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_course_course', to='course.course', verbose_name='درس'),
        ),
        migrations.AlterField(
            model_name='reviewgrade',
            name='result_text',
            field=models.TextField(blank=True, null=True, verbose_name='پاسخ تجدیدنظر'),
        ),
        migrations.AlterField(
            model_name='reviewgrade',
            name='review_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن تجدیدنظر'),
        ),
        migrations.AlterField(
            model_name='reviewgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_course_student', to='accounts.student', verbose_name='دانشجو'),
        ),
        migrations.AlterField(
            model_name='termdrop',
            name='educational_deputy_descr',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات معاون آموزشی'),
        ),
        migrations.AlterField(
            model_name='termdrop',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_drop_req_student', to='accounts.student', verbose_name='دانشجو'),
        ),
        migrations.AlterField(
            model_name='termdrop',
            name='student_descr',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات دانشجو'),
        ),
        migrations.AlterField(
            model_name='termdrop',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_drop_req_term', to='college.term', verbose_name='ترم'),
        ),
    ]
