from .serializer_professor import ProfessorSerializerITAdmin
from .change_password_action import ChangePasswordActionSerializer
from .change_password_request import ChangePasswordRequestSerializer
from .professor import ProfessorSerializer, ProfessorSerializerAllFields
from .student import StudentSerializer, StudentSerializerAllFields
from .logout import LogoutSerializer
