from .serializer_professor import ProfessorSerializerITAdmin
from .change_password_action import ChangePasswordActionSerializer
from .change_password_request import ChangePasswordRequestSerializer
from .logout import LogoutSerializer
from .serializer_student import StudentSerializer, StudentSerializerAllFields, StudentSerializerITAdmin
from .serializer_professor import ProfessorSerializer,ProfessorSerializerAllFields, ProfessorSerializerITAdmin
