# Generated by Django 4.2.4 on 2023-11-21 22:09

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_alter_faculty_name_alter_fieldofstudy_degree_and_more'),
        ('accounts', '0003_alter_educationaldeputy_faculty_and_more'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='co_requisite',
            field=models.ManyToManyField(blank=True, to='course.course', verbose_name='هم نیازها'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('core', 'عمومی'), ('specialized', 'تخصصی'), ('foundation', 'پایه'), ('elective', 'اختیاری')], max_length=50, verbose_name='نوع درس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(verbose_name='تعداد واحد درس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_faculty', to='college.faculty', verbose_name='دانشکده ارایه دهنده'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام درس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pre_requisite',
            field=models.ManyToManyField(blank=True, to='course.course', verbose_name='پیش نیازها'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_course_course', to='course.course', verbose_name='نام درس'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='course_state',
            field=models.CharField(choices=[('passed', 'قبول'), ('failed', 'مردود')], max_length=50, verbose_name='وضعیت درس'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='grade',
            field=models.IntegerField(verbose_name='نمره دانشجو'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_course_term', to='college.term', verbose_name='ترم اخذ شده'),
        ),
        migrations.AlterField(
            model_name='termcourse',
            name='capacity',
            field=models.IntegerField(verbose_name='ظرفیت درس'),
        ),
        migrations.AlterField(
            model_name='termcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_course_course', to='course.course', verbose_name='نام درس'),
        ),
        migrations.AlterField(
            model_name='termcourse',
            name='day',
            field=models.IntegerField(choices=[(1, 'شنبه'), (2, 'یکشنبه'), (3, 'دوشنبه'), (4, 'سه شنبه'), (5, 'چهارشنبه'), (6, 'پنجشنبه'), (7, 'جمعه')], verbose_name='روز'),
        ),
        migrations.AlterField(
            model_name='termcourse',
            name='exam_date_time',
            field=django_jalali.db.models.jDateTimeField(verbose_name='زمان امتحان'),
        ),
        migrations.AlterField(
            model_name='termcourse',
            name='exam_venue',
            field=models.CharField(max_length=50, verbose_name='مکان امتحان'),
        ),
        migrations.AlterField(
            model_name='termcourse',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_course_professor', to='accounts.professor', verbose_name='استاد درس'),
        ),
        migrations.AlterField(
            model_name='termcourse',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_course_term', to='college.term', verbose_name='ترم تحصیلی'),
        ),
        migrations.AlterField(
            model_name='termcourse',
            name='time',
            field=models.TimeField(verbose_name='زمان'),
        ),
    ]
