# Generated by Django 4.2.4 on 2023-11-21 22:09

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_educationaldeputy_faculty_and_more'),
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=256, verbose_name='نام دانشکده'),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='degree',
            field=models.CharField(max_length=256, verbose_name='مقطع'),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_of_study_faculty', to='college.faculty', verbose_name='دانشکده'),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='group',
            field=models.CharField(max_length=256, verbose_name='گروه آموزشی'),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='name',
            field=models.CharField(max_length=256, verbose_name='نام رشته'),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='units',
            field=models.IntegerField(verbose_name='تعداد واحد'),
        ),
        migrations.AlterField(
            model_name='term',
            name='classes_end_time',
            field=django_jalali.db.models.jDateTimeField(verbose_name='زمان پایان کلاس ها'),
        ),
        migrations.AlterField(
            model_name='term',
            name='classes_start_time',
            field=django_jalali.db.models.jDateTimeField(verbose_name='زمان شروع کلاس ها'),
        ),
        migrations.AlterField(
            model_name='term',
            name='emergency_cancellation_end_time',
            field=django_jalali.db.models.jDateTimeField(verbose_name='زمان پایان حذف اضطراری'),
        ),
        migrations.AlterField(
            model_name='term',
            name='exams_start_time',
            field=django_jalali.db.models.jDateField(verbose_name='زمان شروع امتحانات'),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(max_length=256, verbose_name='نام ترم'),
        ),
        migrations.AlterField(
            model_name='term',
            name='professors',
            field=models.ManyToManyField(blank=True, related_name='term_professor', to='accounts.professor', verbose_name='اساتید'),
        ),
        migrations.AlterField(
            model_name='term',
            name='selection_end_time',
            field=django_jalali.db.models.jDateTimeField(verbose_name='زمان پایان انتخاب واحد'),
        ),
        migrations.AlterField(
            model_name='term',
            name='selection_start_time',
            field=django_jalali.db.models.jDateTimeField(verbose_name='زمان شروع انتخاب واحد'),
        ),
        migrations.AlterField(
            model_name='term',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='term_student', to='accounts.student', verbose_name='دانشجو ها'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_end_time',
            field=django_jalali.db.models.jDateField(verbose_name='زمان پایان ترم'),
        ),
        migrations.AlterField(
            model_name='term',
            name='update_end_time',
            field=django_jalali.db.models.jDateTimeField(verbose_name='زمان پایان ترمیم'),
        ),
        migrations.AlterField(
            model_name='term',
            name='update_start_time',
            field=django_jalali.db.models.jDateTimeField(verbose_name='زمان شروع ترمیم'),
        ),
    ]
