# Generated by Django 4.2.4 on 2023-11-21 22:09

import accounts.models.user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
        ('course', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationaldeputy',
            name='faculty',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='educational_deputy_faculty', to='college.faculty', verbose_name='دانشکده'),
        ),
        migrations.AlterField(
            model_name='educationaldeputy',
            name='field_of_study',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='educational_deputy_field_of_study', to='college.fieldofstudy', verbose_name='رشته'),
        ),
        migrations.AlterField(
            model_name='educationaldeputy',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='یوزر'),
        ),
        migrations.AlterField(
            model_name='itadmin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='یوزر'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='degree',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor_degree', to='accounts.degree', verbose_name='مرتبه'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='expertise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor_expertise', to='accounts.expertise', verbose_name='تخصص'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='faculty',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor_faculty', to='college.faculty', verbose_name='دانشکده'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='field_of_study',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor_field_of_study', to='college.fieldofstudy', verbose_name='رشته'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='past_teaching_courses',
            field=models.ManyToManyField(blank=True, related_name='professor_past_courses', to='course.course', verbose_name='دروس تدریسی گذشته'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor_user', to=settings.AUTH_USER_MODEL, verbose_name='یوزر'),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_years',
            field=models.IntegerField(verbose_name='سنوات'),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses_passed',
            field=models.ManyToManyField(blank=True, related_name='student_courses_passed', to='course.course', verbose_name='دروس گذرانده'),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses_taken',
            field=models.ManyToManyField(related_name='student_courses_taken', to='course.course', verbose_name='دروس در حال گذراندن'),
        ),
        migrations.AlterField(
            model_name='student',
            name='entry_term',
            field=models.IntegerField(choices=[(1, 'نیمه اول'), (2, 'نیمه دوم')], verbose_name='ترم ورودی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='entry_year',
            field=django_jalali.db.models.jDateField(verbose_name='سال ورودی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_faculty', to='college.faculty', verbose_name='دانشکده'),
        ),
        migrations.AlterField(
            model_name='student',
            name='field_of_study',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_field_of_study', to='college.fieldofstudy', verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='معدل'),
        ),
        migrations.AlterField(
            model_name='student',
            name='military_service_status',
            field=models.CharField(choices=[('SBJ', 'مشمول'), ('MEE', 'معافیت تحصیلی'), ('MES', 'پایان خدمت')], max_length=3, verbose_name='وضعیت نظام وظیفه'),
        ),
        migrations.AlterField(
            model_name='student',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_supervisor', to='accounts.professor', verbose_name='استاد راهنما'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='یوزر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user.upload_dir, verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره کاربری'),
        ),
    ]
