# Generated by Django 4.2.7 on 2023-11-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('accounts', '0004_alter_student_field_of_study_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='professor',
            name='past_teaching_courses',
            field=models.ManyToManyField(blank=True, related_name='professor_past_courses', to='course.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses_passed',
            field=models.ManyToManyField(blank=True, related_name='student_courses_passed', to='course.course'),
        ),
    ]
