POST http://127.0.0.1:8000/accounts/login/token/
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###

POST http://192.168.2.11/accounts/login/token/
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}