POST http://127.0.0.1:8000/accounts/change-password-request/
Content-Type: application/json

{
  "email": "sahand.u99@gmail.com"
}

###

POST http://127.0.0.1:8000/accounts/change-password-action/Mg/bxyvq2-706f06080a62e75dcf276e2bfe1a5428/
Content-Type: application/json

{
  "new_password": "test-new-password"
}