
from .faculty_educational_deputy import IsFacultyEducationalDeputy
from .it_admin import IsITAdmin
from .professor import IsProfessor
from .student import IsStudent
from .EducationalDeputyOrStudentOrProfessor import EducationalDeputyOrStudentOrProfessorPermission
