from .change_password_request import ChangePasswordRequestView
from .change_password_action import ChangePasswordActionView
from .logout import LogoutView
from .view_professor import ProfessorViewSet, ProfessorViewSetITAdmin
from .view_student import StudentViewSetITAdmin, StudentViewSet
